apiVersion: v2
appVersion: v0.16.2106
description: API Support for your favorite torrent trackers
name: jackett
version: 7.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- jackett
- torrent
home: https://github.com/k8s-at-home/charts/tree/master/charts/jackett
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-banner.png
sources:
- https://hub.docker.com/r/linuxserver/jackett/
- https://github.com/Jackett/Jackett
maintainers:
- name: asdfffffff
  email: afdsafds@mailinator.com
metadata:
  name: hello-world
  labels:
    app: hello-world
  annotations:
    dev.okteto.com/auto-ingress: "true"

image:
  repository: linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: version-v0.16.2106

strategy:
  type: Recreate

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

service:
  enabled: true
  type: ClusterIP
  port:
    port: 9117

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false

  torrentblackhole:
    enabled: false
    emptyDir: false
    mountPath: /downloads
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""

replicas: 1
controllerType: deployment

strategy:
  ## For Deployments, valid values are Recreate and RollingUpdate
  ## For StatefulSets, valid values are OnDelete and RollingUpdate
  ## DaemonSets ignore this
  type: RollingUpdate
