name: jackett
services:
  jackett:
    public: true
    image: linuxserver/jackett:latest
    build: .
    replicas: 1
    ports:
      - 9117
    resources:
      cpu: 100m
      memory: 128Mi
      storage: 1Gi
    volumes:
      - /config
