name: jackett
services:
  jackett:
    labels:
      app: jackett
    public: true
    image: linuxserver/jackett:v0.18.290-ls33
    replicas: 1
    ports:
      - 9117
    resources:
      cpu: 100m
      memory: 512Mi
      storage: 1Gi
    volumes:
      - /config
