name: jackett
labels:
  app.kubernetes.io/part-of: vote
  app.kubernetes.io/component: api
services:
  jackett:
    public: true
    image: linuxserver/jackett:latest
    replicas: 1
    ports:
      - 9117
    resources:
      cpu: 100m
      memory: 512Mi
      storage: 1Gi
    volumes:
      - /config
